### ISSUE TITLE
pybrm : Oracle Wallet support

### ISSUE THREAD

**Issue by mkothar2** [mkmoisen/pybrm#2]
Can pybrm be enhanced to add new functions to query Oracle Wallet for retrieving few entries and also function to update wallet .

**Comment by mkmoisen** [comment]
@mkothar2 would you please link me to some example documentation which contains the C code for interacting with Oracle Wallet? So far I have not used this in my normal work but I would be happy to add it.

**Comment by mkmoisen** [comment]
@mkothar2 I do not see any APIs available for interacting with the Oracle Wallet at the developer reference:

https://docs.oracle.com/en/industries/communications/billing-revenue/12.0/dev-reference/index.html

I used this document to wrap most/all of the BRM C APIs into pybrm.

**Comment by mkothar2** [comment]
We have internal tools like pin_config_editor and pin_crypt_app which gets/sets values in Oracle Wallet 

Also we have DB/java tool orapki . It can be called directly from pybrm API's

**Comment by mkmoisen** [comment]
I would recommend that you call orapki from python using the `subprocess` module.

```
import subprocess

p = subprocess.run(['orapki', 'wallet', 'display', '-wallet', '/path/to/dbhome_1/owm/wallets'], shell=True, stdout=subprocess.PIPE)

print(p.stdout)
```
