### ISSUE TITLE
Fatal error: can't find the pinlog function. Error=.../lib/libpcmext64.so: undefined symbol: pinlog

### ISSUE THREAD

**Issue by JoostPerdok** [mkmoisen/pybrm#5]
I am encountering this error when running pybrm on amazon ec2-instance:

> Fatal error: can't find the pinlog function. Error=/home/ec2-user/BRM/lib/libpcmext64.so: undefined symbol: pinlog.

Code:
```
import pybrm
c =  pybrm.Client()
f = c.flist()
```

The error occurs at calling the c.flist() function, creating the client gives no problems.

Any idea on how to fix this?

**Comment by mkmoisen** [comment]
Hi @JoostPerdok , is your `PIN_HOME` environment variable set correctly?

In my $PIN_HOME/lib directory, I have a libpcmext64.so file, which comes as part of the BRM installation. 

Are you able to compile and run a regular C program that uses the BRM library?

**Comment by JoostPerdok** [comment]
Hi @mkmoisen, thank you for your reply.

My `PIN_HOME` environment variable is set, and I also have t he libpcmext64.so file in the /lib directory.
I can also run a C program that uses the BRM library.

I have also checked the /include directory, and there is a file called pinlog.h, where a pinlog() function is declared. It seems like the compiler cannot find the header files when I run it through pybrm. I have also tried setting the `C_INCLUDE_PATH` environment variable, but the error remains.

**Comment by mkmoisen** [comment]
Hi @JoostPerdok ,

Would you please send me

1) A small C program that opens a CM and creates an flist.
2) The commands you are using to fully compile and run this file

I'll try to run that on my system and see if there is a discrepancy. 

Which version of BRM are you using?

Is there a stack trace? Or does it just print the `Fatal error :...` message and exit? If there is a stack trace please send it.

In addition, you may want to take a look through the [setup.py](https://github.com/mkmoisen/pybrm/blob/master/setup.py) script and see if there is anything off. Notably the `include_dirs` and `library_dirs`.

**Comment by JoostPerdok** [comment]
Hi @mkmoisen,

I managed to "fix" the issue by using an AWS EC2 instance with Amazon Linux 2 OS, instead of Amazon Linux 2023 OS.
So it seems to be a problem with the operating system, although I'm not sure what the problem is exactly.

Thank you for helping!

**Comment by mkmoisen** [comment]
Hi @JoostPerdok 

Ah, interesting. 

Please let me know if you have any other issues with pybrm.

**Comment by mkmoisen** [comment]
Hi @JoostPerdok Have you found pybrm useful or have you run into any other issues? Thanks.

**Comment by JoostPerdok** [comment]
Hi @mkmoisen,

I have found pybrm very useful and have not run into any problems.
